#!/bin/bash -f

#WMII_ROOT="${WMII_CONFPATH%%:*}"
: ${WMII_ROOT?}

WMII_LOCATION=home
WMII_HARDWARE_SYSTEM=$(sudo dmidecode -s system-product-name)

WMII_SCREENS=$(xrandr |grep " connected " | wc -l)

ln -sf ${HOME}/.Xresources.generic ${HOME}/.Xresources.wmii
case ${WMII_HARDWARE_SYSTEM} in
	MacBook*)
		WMII_HARDWARE=laptop
        # change font if primary screen is on MacBook
        # high res screen
        if [ ${WMII_SCREENS} -eq 1 ]; then
            ln -sf ${HOME}/.Xresources.macbook ${HOME}/.Xresources.wmii
        fi
		;;
	*)
		WMII_HARDWARE=desktop
esac

export WMII_LOCATION WMII_HARDWARE WMII_SCREENS
#xset r rate 200 40

source ${WMII_ROOT}/wmii.conf

mn_bootstrap;
logger INFO "bootstrapping nomad-wmii system...complete"

# load ssh keys into ssh-agent
# generic and host-specific
ssh-add
SSH_KEY_HOST=${HOME}/.ssh/id_rsa_${HOSTNAME}
test -r ${SSH_KEY_HOST} && ssh-add ${SSH_KEY_HOST}

#. Open up /event for reading; and read line by line:
logger INFO "loop(main)...start"
wmiir read /event | while read line; do
    set -- ${line}
    mn_event_handler $*
done
logger INFO "loop(main)...stop"
