#!/bin/bash -f

export WMII_ROOT="${HOME}/.wmii-hg"
: ${WMII_ROOT?}

WMII_LOCATION=home
WMII_HARDWARE_SYSTEM="$(sudo dmidecode -s system-product-name)"

WMII_SCREENS=$(xrandr |grep " connected " | wc -l)

ln -sf ${HOME}/.Xresources.generic ${HOME}/.Xresources.wmii
[ -e "${HOME}/.Xresources.${WMII_HARDWARE_SYSTEM// /_}" ] && ln -sf "${HOME}/.Xresources.${WMII_HARDWARE_SYSTEM// /_}" "${HOME}/.Xresources.wmii"

case ${WMII_HARDWARE_SYSTEM} in
	MacBook*) WMII_HARDWARE=laptop ;;
	*) WMII_HARDWARE=desktop ;;
esac

export WMII_LOCATION WMII_HARDWARE WMII_SCREENS WMII_HARDWARE_SYSTEM
#xset r rate 200 40

source ${WMII_ROOT}/wmii.conf

mn_bootstrap;
logger INFO "bootstrapping nomad-wmii system...complete"

# load ssh keys into ssh-agent
# generic and host-specific
ssh-add
SSH_KEY_HOST=${HOME}/.ssh/id_rsa_${HOSTNAME}
test -r ${SSH_KEY_HOST} && ssh-add ${SSH_KEY_HOST}

#. Open up /event for reading; and read line by line:
logger INFO "loop(main)...start"
wmiir read /event | while read line; do
    set -- ${line}
    mn_event_handler $*
done
logger INFO "loop(main)...stop"
