#!/bin/bash
. "${WMII_CONFPATH%%:*}/statusbar.conf"
THEME=SW
SYMBOL=2600

if sb_ready 1; then
    lck ${LOCK_SB_MODULE} on

    brightness=$(user_brightness status)
    case ${BUTTON} in
        ${MOUSE_U}) $(user_brightness up);;
        ${MOUSE_D}) $(user_brightness down);;
        ${MOUSE_M}) $(user_brightness toggle);;
    esac

    DATA=${brightness%%.*}
    sb_write_cache "${DATA}"

    lck ${LOCK_SB_MODULE} off
fi
sb_read_cache
