#!/bin/bash
. "${WMII_CONFPATH%%:*}/statusbar.conf"
THEME=SW
SYMBOL=266a

requires amixer || exit 97

if sb_ready 1; then
    lck ${LOCK_SB_MODULE} on
    status=$(user_volume status)
    read vol mute <<< "$(user_volume status)"
    case ${BUTTON} in
        ${MOUSE_L}) $(user_volume toggle);;
        ${MOUSE_U}) $(user_volume up);;
        ${MOUSE_D}) $(user_volume down);;
    esac

    if [ "${mute}" == "off" ]; then
        sb_escalate CRIT
    fi

    DATA=${vol}
    sb_write_cache "${DATA}"
    lck ${LOCK_SB_MODULE} off
fi
sb_read_cache
