#!/bin/bash
exit
. "${WMII_ROOT}/statusbar.conf"
THEME=NW
SYMBOL=25f2

requires lck || exit 97
requires openconnect || exit 97

if sb_ready 10; then
    lck ${LOCK_SB_MODULE} on

    case ${BUTTON} in
        ${MOUSE_L})
                sudo openconnect -b offvpn
            ;;
        ${MOUSE_R})
                sudo pkill openconnect
            ;;
    esac
    IP=$(ip tun0)
    if [ -z "${IP}" ]; then
        SB_ALERT=DULL
    else
        DATA="${IP}"
    fi

    sb_write_cache "${DATA}"
    lck ${LOCK_SB_MODULE} off
fi
sb_read_cache
