reset:
	chmod 600 [0-9][0-9]-*

	# generic
	chmod 700 31-clipboard 60-net 80-mem 81-cpu 82-hdd 97-kbd 99-time

	# media
	# chmod 700 09-volume 10-muzik

	# laptop
  	# chmod 700 08-brighness 89-battery

	# cloud
	# chmod 700 11-dropbox

	# network
	# chmod 700 33-nc 50-daemonized 65-sock 68-vpn 69-internetz

	# sysadmin
	# chmod 700 35-screen 36-jira 62-tmux

	# misc
	#chmod 700 98-work 88-entropy
